{
  "contest": 278,
  "handle": "0xbrett8571",
  "risk": "3",
  "title": "Potential for reentrancy attacks due to the use of the `call()` function in the `execute()` function, which doesn't block the execution of the calling contract.",
  "issueId": 918,
  "issueUrl": "https://github.com/code-423n4/2023-08-dopex-findings/issues/918"
}